### ISSUE TITLE
Create icon for this fork

### ISSUE THREAD

**Issue by jurkov** [Bytespeicher/BytespeicherTrayIcon#1]
Create icon for this tiny fork.

**Comment by vinird** [comment]
Hi @jurkov I can help you. Can you show me one example?

**Comment by jurkov** [comment]
Maybe something like https://status.bytespeicher.org/status_closed.png and https://status.bytespeicher.org/status_open.png. It should be CC license, so it could be used in open source software-

**Comment by vinird** [comment]
Ok, working on it.

**Comment by jurkov** [comment]
Thank you very much. Your icon is the tray icon now :-).

**Comment by vinird** [comment]
Nice!
