### ISSUE TITLE
Add translation for Hindi

### ISSUE THREAD

**Issue by jurkov** [Bytespeicher/BytespeicherTrayIcon#9]
If you need some advice how to translate a qt project please take a look at https://doc.qt.io/qt-5/qtlinguist-arrowpad-example.html. 

Please take qt linguist and open lang/main_hi-IN.ts for translation.

**Comment by sanchaymittal** [comment]
@jurkov I can help you. Just show me example of any translated file?

**Comment by jurkov** [comment]
Just Take a look at the language folde
